highlighter: rouge
markdown: kramdown
columnist:
  paths:
  - _posts
prose:
  rooturl: '_posts'
permalink: /:lang/:categories/:title/
#baseurl: 'http://transcaucasiantrail.org/'
#baseurl: 'http://localhost:4000/'
