highlighter: rouge
markdown: kramdown
columnist:
  paths:
  - _posts
permalink: /:lang/:categories/:title/
prose:
  rooturl: '_posts'
  media: 'assets/blog/media'
  metadata:
    _posts:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "false"
      - name: "layout"
        field:
          element: "hidden"
          label: "layout"
          value: "blog"
      - name: "title"
        field:
          label: "title"
          element: "text"
          value: "An Awesome Title"
      - name: "permalink"
        field:
          element: "text"
          label: "permalink"
          value: "/en/blog/title-of-post"
      - name: "lang"
        field:
          element: "hidden"
          label: "lang"
          value: "en"
      - name: "category"
        field:
          element: "hidden"
          label: "category"
          value: "blog"
      - name: "author"
        field:
          element: "select"
          label: "author"
          placeholder: "Choose author"
          value: personal
          options:
            - name: "Paul Stephens"
              value: Paul Stephens
            - name: "Jeff Haack"
              value: Jeff Haack
            - name: "Marta Mills"
              value: Marta Mills
            - name: "Tako Kobakhidze"
              value: Tako Kobakhidze
            - name: "Tom Allen"
              value: Tom Allen
            - name: "Alessandro Mambelli"
              value: Alessandro Mambelli
      - name: "thumb-big"
        field:
          element: "text"
          label: "thumb-photo (Ideally 480x125)"
          value: "/assets/blog/media/default-thumb.jpg"
      - name: "thumb-fb"
        field:
          element: "text"
          label: "Social Media photo (Ideally landscape, more wide than high)"
          value: "/assets/blog/media/default-fb.jpg"
t:
  en:
    navbar: 
      home:  "Homey"
      about: "About the TCT"
      goals: "Goals"
      faq: "FAQ"
      get-involved: "Get Involved"
      gear: "Gear"
      blog: "Blog"
  ka:
    navbar: 
      home:  "მთავარი"
      about: "About the TCT"
      goals: "მიზნები"
      faq: "კითხვა-პასუხი"
      get-involved: "შემოგვიერთდი"
      gear: "Gear"
      blog: "Blog"
  hy:
    navbar: 
      home:  "Homey"
      about: "About the TCT"
      goals: "Goals"
      faq: "FAQ"
      get-involved: "Get Involved"
      gear: "Gear"
      blog: "Blog"
  ru:
    navbar: 
      home:  "Homey"
      about: "About the TCT"
      goals: "Goals"
      faq: "FAQ"
      get-involved: "Get Involved"
      gear: "Gear"
      blog: "Blog"
#baseurl: 'http://transcaucasiantrail.org/'
#baseurl: 'http://localhost:4000/'
